import type { Metadata } from "next";
import { Inter, Russo_One } from "next/font/google";
import "@/app/globals.css";
import {BaseLayout} from "@/app/layouts";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
})

const russoOne = Russo_One({
    variable: "--font-russo-one",
    subsets: ["latin"],
    weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${russoOne.variable} h-full antialiased`}
    >
        <body className="min-h-screen flex flex-col w-full font-sans">
            <BaseLayout>
                {children}
            </BaseLayout>
        </body>
    </html>
  );
}
